### ISSUE TITLE
Running ipv6nat from Docker image removes IPv6 addresses from all interfaces on Debian 8

### ISSUE THREAD

**Issue by mkuron** [robbertkl/docker-ipv6nat#10]
When I run `docker run -d --restart=always -v /var/run/docker.sock:/var/run/docker.sock:ro -v /lib/modules:/lib/modules:ro --privileged --net=host robbertkl/ipv6nat` on Debian 8 (Kernel 4.9.0-0.bpo.2-amd64 from jessie-backports, Docker 17.04.0), all inet6 addresses, including the link-local ones, are removed from all interfaces and thus IPv6 communication ceases to work. To recover, the container needs to be stopped and removed and the host needs to be rebooted or have its inet6 addresses manually restored.

If instead I download the release version and run it directly on the host, the above does not happen and the address translation is performed correctly.

**Comment by robbertkl** [comment]
Thanks @mkuron for reporting. This is the first I hear about an issue like this, it doesn't occur on any other hosts / OS'es I'm aware of.

As you can see in `Dockerfile.amd64`, all it does is run the release version inside of a (privileged) Alpine Linux container. The first time ip6tables is called, it loads the needed IPv6 related kernel modules if they weren't loaded yet. Perhaps this causes side effects? But on the other hand, running the release version directly on the host OS should do the same.

Is it possible for you to test it on Debian 8 with another container base OS, by manually building the image from a modified Dockerfile? Just to figure out if it's caused by "running in a container" or "running in an Alpine container"..

**Comment by mkuron** [comment]
The only difference is probably that the ip6tables binary came from Alpine; perhaps it's not fully compatible with Debian's kernel. `ip6tables --list` on the host does show that the appropriate rules were created though.
I will test as requested and report back in a few days.

**Comment by robbertkl** [comment]
Much appreciated!

**Comment by mkuron** [comment]
Appears to be an issue in Docker: `--net=host` currently disables IPv6 on the host. It has been fixed, but not yet released: https://github.com/docker/libnetwork/pull/1711

**Comment by robbertkl** [comment]
Good to know, thanks!
