### ISSUE TITLE
Setting IP Address to docker0 interface

### ISSUE THREAD

**Issue by heinemml** [robbertkl/docker-ipv6nat#2]
Hi,

thanks for fixing #1 so fast. 

I got another related one.

When I use the `com.docker.network.bridge.host_binding_ipv6` option the ip6tables rules are now created fine. But my IP is not reachable from the outside. 

I took a look how this handled in the IPv4 case. 
When I use ` "com.docker.network.bridge.host_binding_ipv4"="1.2.3.4"` the ip address 1.2.3.4 is assigned to the docker0 interface. I guess something equivalent should be done when using the `com.docker.network.bridge.host_binding_ipv6` option.

Of course I can add the ip address manually to the docker0 interface. But if I restart docker the IP is gone, I guess it flushes the assigned IPs on start (after `service docker stop` it's still there).

Do you think this is in the scope of this progress? Or any other idea how to achieve this?

**Comment by robbertkl** [comment]
Hi, thanks again, just keep 'em coming!

Since `docker0` is the bridge interface for the default `bridge` network, I assume you've assigned 1.2.3.4 using `--ip=1.2.3.4` on the Docker daemon. Is that correct?

I've just created a user-defined network like this:

```
docker network create \
  -o com.docker.network.bridge.host_binding_ipv4=1.2.3.4 \
  -o com.docker.network.bridge.name=br-test \
  test
```

However, I don't see this IP auto-configured on any interface, not on `docker0` and not on `br-test`.

My guess is that the auto assignment to the `docker0` interface is a "bonus feature" of the `--ip=` flag. If you supply a non-existing IP address there, it will create it for you. Since there is no IPv6 equivalent of this flag, and the binding option is therefor only available on user-defined networks, I don't think there's a good place for docker-ipv6nat to do this. After all, Docker doesn't do it for IPv4 on user-defined networks either.

I believe binding is really meant for IP addresses that are already configured on your system, outside of Docker, in your network configuration. Compare this to other network daemons, like for example `sshd`. By default it binds on all addresses, but by supplying a `ListenAddress` in `sshd_config` you can bind it to a specific (pre-configured) address. `sshd` will fail to start when this address is not configured (unless `net.ipv4.ip_nonlocal_bind=1`).

What do you think?

**Comment by heinemml** [comment]
Hi,

you are right, I had the ipv4 address assigned before via the --ip flag before I was switching to the user-defined network. For some reason the IPv6 address gets removed on docker start but the ipv4 stays.

I now just added both, my IPv4 and my IPv6 address for the network to the eth0 interface, so it is independent from docker startup or anything.

Seems to work fine, so nothing to be done here ;)

Just some background on what I'm using ipv6nat for. I have a gitlab installation where I want to send the http(s) traffic through an nginx proxy which handles all the letsencrypt renewal and provisioning stuff. But for git I need the ssh port to be reachable on the same IP address. So the nat solution is the only way I found to achieve that. 

So thanks for your solution and your help! Cheers.

**Comment by robbertkl** [comment]
Hi, I have a similar solution as far as Let's Encrypt proxy (I created https://github.com/robbertkl/docker-proxy for this). I'm also running a mail server and basically wanted everything to be reachable on IPv6. For mail, it's also important the original source IPv6 address ends up in the mail container, so SPF filters function properly.

Thanks for using docker-ipv6nat and let me know if you run into any other issues.
